### ISSUE TITLE
Can't find log files, looks for nick instead of network

### ISSUE THREAD

**Issue by psy-q** [robinsmidsrod/znc-log-viewer#1]
I have this issue on Debian jessie:

```
user@server:~$ znc-log-viewer nick
Can't open directory /home/user/.znc/users/nick/networks/nick/moddata/log: No such file or directory at /home/user/bin/znc-log-viewer line 95.
```

And if I specify a network:

```
user@server:~$ znc-log-viewer ircnet nick
Please specify a valid user to search:
nick
```

I'm using ZNC 1.4 as offered by Debian. Do I need a newer one?

**Comment by robinsmidsrod** [comment]
@psy-q Normally you'd just call the command without parameters to find out which networks/users you can use. In my case I call them `freenode` and `quakenet`, after the IRC networks I connect to.

Then you need to specify which log folder you want, e.g. the one for the `#ipxe` channel. That should be specified like this: `znc-log-viewer freenode \#ipxe`. If you don't specify a nick/channel then you should get a list of the valid ones (with a number in parentheses with how many log files are around for that channel).

If you also want to filter on some text in the log you specify that as the next parameter: `znc-log-viewer freenode \#ipxe 201607` to show everything from July 2016 in the Freenode #ipxe channel.

**Comment by psy-q** [comment]
That doesn't make a difference for me. It only lists one user but does not accept that as argument, and specifying the network or channel doesn't seem to work. It complains that no user is given if I use the sequence of options you describe, but if I do give a username it doesn't find the logfiles.

Let's say the user is "psy-q", these are the relevant dirs:

```
.znc/
.znc/users
.znc/users/psy-q
.znc/users/psy-q/networks
.znc/users/psy-q/networks/debian
.znc/users/psy-q/networks/debian/moddata
.znc/users/psy-q/networks/debian/moddata/log
.znc/users/psy-q/networks/ircnet
.znc/users/psy-q/networks/ircnet/moddata
.znc/users/psy-q/networks/ircnet/moddata/log
```

And there is for example:

```
.znc/users/psy-q/networks/ircnet/moddata/log/#linux_20160713.log
```

znc-log-viewer says:

```
znc-log-viewer
Please specify a valid user to search:
psy-q
```

And:

```
znc-log-viewer ircnet \#linux 201607
Please specify a valid user to search:
psy-q
```

When I give a nick and nothing else it tries to open the wrong file:

```
znc-log-viewer psy-q
Can't open directory /home/foo/.znc/users/psy-q/networks/psy-q/moddata/log: No such file or directory at /home/rca/bin/znc-log-viewer line 95.
```

It substitutes the username twice in the path instead of the network name for some reason. It doesn't seem like any of the options change anything even though the log files are there. I'm wondering if ZNC has changed log file locations between versions and mine is too old? In 1.4, they all land in `.znc/users/psy-q/networks/ircnet/moddata/log/#linux_20160713.log` for example.

**Comment by robinsmidsrod** [comment]
@psy-q I know now what the problem is. Instead of having a single user with multiple networks, I use one user per network, so that in my IRC client I have one connection for each network, so they show up in different tabs. using a single znc user with multiple networks per user is what you have, which is not quite compatible with my configuration. You need to modify the `get_znc_user_map()` sub to allow for multiple networks per user. What you could do instead of asking for the username as first argument is to skip that one, iterate all of the users present and filter on the networks available instead. Or alternatively, an option could be introduced to allow four parameters, where znc user and network are two separate arguments. Last one is probably better.

**Comment by psy-q** [comment]
Okay, I'll think about that a bit, maybe I can manage to do a pull request (my Perl is very rusty). It's odd, though, this is the default out-of-the-box configuration of ZNC and the log module. Weird that no one mentioned this earlier?

**Comment by robinsmidsrod** [comment]
@psy-q It's got nothing to do with the default configuration, it's just about how you use it. And my use-case is slightly different from yours. That's all. It is odd that nobody's mentioned it before, though. Maybe I'm not the only one that runs one user per network?

**Comment by robinsmidsrod** [comment]
@psy-q You should now be able to use the tool with multiple networks per user, or user and network names being different. Please report back how it works. Reopen if necessary.

**Comment by psy-q** [comment]
This works extremely well, thanks a lot! :beers:
